format = """
[](#4c566a)\
$os\
$username\
[](bg:#a3be8c fg:#4c566a)\
$directory\
[](fg:#a3be8c bg:#b48ead)\
$git_branch\
$git_status\
[](fg:#b48ead bg:#81a1c1)\
$c\
$golang\
$nodejs\
$rust\
$python\
[](fg:#81a1c1 bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#4c566a fg:#d8dee9"
style_root = "bg:#4c566a fg:#d8dee9"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#4c566a fg:#d8dee9"
disabled = true # Disabled by default

[directory]
style = "bg:#a3be8c fg:#d8dee9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
symbol = ""
style = "bg:#81a1c1 fg:#d8dee9"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#81a1c1 fg:#d8dee9"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#b48ead fg:#d8dee9"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#b48ead fg:#d8dee9"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#81a1c1 fg:#d8dee9"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#81a1c1 fg:#d8dee9"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#81a1c1 fg:#d8dee9"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A fg:#d8dee9"
format = '[ $time ]($style)'
